#!/bin/bash
 
# Set up an icon tray

wmname LG3D

if [ -x /usr/bin/nm-applet ] ; then
   nm-applet&
fi

if [ -x /usr/bin/gnome-volume-control-applet ] ; then
   gnome-volume-control-applet&
fi

skype&

dropbox start&

urxvtd -q -f -o

xrdb -merge /home/ikke/.Xresourses 

exec awesome
